<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introducción a numpy:
</p><br>

### Características:

- **ndarreglos:** arreglos n-dimensionales del mismo tipo de datos que son más eficientes en espacio y tiempo. Hay métodos hechos para los arreglos numpy sin la necesidad de usar loops. 
- **Broadcasting:** Herramienta para poder hacer operaciones con arreglos de distintas dimensiones y tamaños.
- **Vectorización:** Capacidad par realizar multiples operaciones numéricas con los arregloss numpy.

<b>Recursos adicionales:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentación</a><br>

<i>Introducción a numpy con python</i> por Ramiro <br>
<i>Introducción a numpy con python</i> por Albert

<a href="https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/"> Jupyter Shortcuts</a><br>

``Cmd + Shift + P``

### nd arreglo numpy

In [9]:
import numpy as np #importa la librería de numpy

an_array = np.array([3, 33, 333]) 
# Tipo de dato
print(type(an_array))

<class 'numpy.ndarray'>


In [10]:
# Obtener la dimensión del arreglo numpy

np.shape(an_array)

(3,)

In [20]:
# No pueden ser de distintos tipos de datos

a = np.array([2,'fo',5.3]) 
b = np.array([2,5,5.3])
c = a+b
print(type(c))

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

### Accediendo a los elementos del arreglo

In [36]:
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [37]:
#Los arreglso son mutables
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)


[888  33 333]


### Matrices

In [39]:
matriz = np.array([[11,12,13],[21,22,23],[2,5,7]])
print(matriz)

[[11 12 13]
 [21 22 23]
 [ 2  5  7]]


In [41]:
print("Accesando a los elementos: [0,0], [0,1], and [1,0] de la matriz: ", matriz[0, 0], ", ",matriz[0, 1],", ", matriz[1, 0])


Accesando a los elementos: [0,0], [0,1], and [1,0] de la matriz:  11 ,  12 ,  21


In [42]:
# Matriz de 2x2 ceros
ex1 = np.zeros((2,2))      
print(ex1) 

[[0. 0.]
 [0. 0.]]


In [43]:
# Matriz 2x2 de 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)

[[9. 9.]
 [9. 9.]]


In [47]:
# Matriz 4x4 de diagonal de 1 y  los demás 0
ex3 = np.eye(4,4)
print(ex3) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [49]:
# Matriz de 1´s
ex4 = np.ones((4,2))
print(ex4)  

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Indexing

In [64]:
# Matriz de 3x4
m = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(m)
index_example = m[0,2]
print("Index example: ",index_example)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Index example:  13


### El operador : significa que toma todos los elementos hasta el final.

``data[desde:hasta]``

* Un elemento antes de "hasta"

```matriz[0:1] toma sólo el índice 0, es del 0 al índice 1, pero no toma el límite superior````
* Si hay índices negativos, se refieren a el índice empezando del final

```matriz[-2:] toma desde los último dos elementos iniciando desde el último elemento hasta el final```

In [55]:

print(" m[0,1:]  = ",m[0,1:]) 

 a[10:]  =  [12 13 14]


In [59]:
# Selecciona todas las filas excepto la última columna
except_last_column = m[:, :-1]
print(except_last_column)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [60]:
# Selecciona todas las filas y sólo la última columna
just_last_column = m[:, -1]
print(just_last_column)

[14 24 34]


### Index booleano

In [54]:
ar = np.array([10, 40, 80, 50, 100]) 
print(ar[ar>50])

[ 80 100]


### Reshape

In [65]:
m.shape

(3, 4)

In [71]:
reshaped_m = m.reshape(4,3)
print("New m reshaped:",reshaped_m, "\n shape:",reshaped_m.shape)

New m reshaped: [[11 12 13]
 [14 21 22]
 [23 24 31]
 [32 33 34]] 
 shape: (4, 3)


### Operaciones aritméticas 

In [72]:
x = np.array([[111,112],[121,122]])
y = np.array([[211.1,212.1],[221.1,222.1]])

In [75]:
# suma
# o x+y
print("suma:\n", np.add(x, y)) 

suma:
 [[322.1 324.1]
 [342.1 344.1]] 



In [76]:
# resta
# o x-y
print("resta:\n", np.subtract(x, y))

resta:
 [[-100.1 -100.1]
 [-100.1 -100.1]]


In [95]:
# multiplicación
# o x*y
print("multiplicación:\n", np.multiply(x, y))
# producto punto, donde numpy sólo que lo maneja como un producto matricial
print("dot:\n",np.dot(x,y))

resta:
 [[23432.1 23755.2]
 [26753.1 27096.2]]
dot:
 [[48195.3 48418.3]
 [52517.3 52760.3]]


In [78]:
# división
# o x/y
print("división:\n", np.divide(x, y))

resta:
 [[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [79]:
# raíz cuadrada
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [80]:
# exponencial (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


## Operaciones estadísticas básicas
* Tener en cuenta que:

``index = 0, son las filas``

``index = 1, son las columnas``

In [81]:
# Generamos una matriz  random de 2x4
random_matriz = 10 * np.random.randn(2,5)
print(random_matriz)

[[ -0.47892828 -17.43629767 -16.4709797  -14.17255235  -6.72902984]
 [ -7.51772254  -8.11591385   2.45309382   4.2479872  -12.21870456]]


In [84]:
# promedio para todos los elementos
print("promedio para todos los elementos:",random_matriz.mean())

promedio para todos los elementos: -7.643904776487107


In [85]:
# Promedio por filas
print(random_matriz.mean(axis = 1))

[-11.05755757  -4.23025198]


In [87]:
# Promedio por columnas
print(random_matriz.mean(axis = 0))

[ -3.99832541 -12.77610576  -7.00894294  -4.96228257  -9.4738672 ]


In [88]:
# mediana por fila
print(np.median(random_matriz, axis = 1))

[-14.17255235  -7.51772254]


In [89]:
# Desviación estándar por fila
print(np.std(random_matriz, axis = 1))

[6.48598808 6.42290987]


### Sorting

In [98]:
sorted = np.array(random_matriz)
sorted.sort()
print(sorted)


[[-17.43629767 -16.4709797  -14.17255235  -6.72902984  -0.47892828]
 [-12.21870456  -8.11591385  -7.51772254   2.45309382   4.2479872 ]]
[[ -0.47892828 -17.43629767 -16.4709797  -14.17255235  -6.72902984]
 [ -7.51772254  -8.11591385   2.45309382   4.2479872  -12.21870456]]


**Encontrando Elementos únicos.**

In [99]:
r = np.array([1,2,1,4,2,1,4,2])

print(np.unique(r))

[1 2 4]


In [100]:
s1 = np.array(['caja','silla','mesa'])
s2 = np.array(['lámpara','mesa','silla'])
print(s1, s2)

['caja' 'silla' 'mesa'] ['lámpara' 'mesa' 'silla']


In [101]:
print( np.intersect1d(s1, s2) ) 

['mesa' 'silla']


In [102]:
print( np.setdiff1d(s1, s2) ) # Elementos de s1 que no están en s2

['caja']


In [103]:
print( np.in1d(s1, s2) ) # Qué elementos de s1 está en s2 booleano

[False  True  True]


### Broadcasting

In [111]:
# 3x4 matriz
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Matriz\n",arrA)
#  4x1 vector
arrB = [0,1,0,2]
print("\nvector\n",arrB)
# distintas dimensiones, empleo del Broadcasting 
print("\nBroadcasting suma:\n",arrA + arrB)

Matriz
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

vector
 [0, 1, 0, 2]

Broadcasting suma:
 [[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]
