<h1>Python tiene varias librerias para hacer tratamiento de datos y trabajar con matrices.</h1>


In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
np.array([1,2,3])

array([1, 2, 3])

nd arreglo numpy

In [3]:
an_array = np.array([3,33,333])
# tipo de dato
print(type(an_array))

<class 'numpy.ndarray'>


In [4]:
# Obtener la dimensión del arreglo numpy
np.shape(an_array)

(3,)

In [5]:
# No pueden ser de distintos tipos de datos 
a= np.array([2, 'fo', 5.3])
b= np.array([2,5,5.3])
c = a+b
print (type(c))

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

<h1>Accediendo a los datos del arreglo </h1>

In [12]:
print(an_array[0],an_array[1],an_array[2])

888 33 333


In [7]:
#Los arreglos son mutables
an_array[0] = 888
print(an_array)

[888  33 333]


 <h1> Matrices</h1>

In [20]:
matriz = np.array([[11,12,13],[21,22,23],[2,5,7]])
print(matriz)

[[11 12 13]
 [21 22 23]
 [ 2  5  7]]


In [21]:
print("Accesando a los elementos: [0,0], [0,1], and [1,0] de la matriz:"matriz[0,0],", "matriz[0,1],", "matriz[1,0]".")

SyntaxError: invalid syntax (<ipython-input-21-9266f7a75b5b>, line 1)